substitutions:
  friendly_name: "Garage door"
  name: "garage-door"

esphome:
  name: "${name}"

external_components:
  - source: components

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

api:
  encryption:
    key: "YK17oHA9Wdfu4ou0vSMPUYwgMseHXHKNJOTieLub5S8="

ota:
  password: "8b43b192aa7dce0042bcf6bd5002f3bc"

packages:
  common: !include common/common.yaml

status_led:
  pin: 25

output:
  - platform: gpio
    id: relay
    pin: 33

button:
  - platform: template
    name: "${friendly_name} press button"
    icon: "mdi:gate"
    on_press:
      then:
        - output.turn_on: relay
        - delay: 300ms
        - output.turn_off: relay

logger:
  level: INFO

cover:
  - platform: as5600_cover
    device_class: garage
    name: Garage door
