substitutions:
  friendly_name: "Garage door"
  name: "garage-door"

esphome:
  name: "${name}"

external_components:
  - source: components

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

api:
  encryption:
    key: "YK17oHA9Wdfu4ou0vSMPUYwgMseHXHKNJOTieLub5S8="

ota:
  password: "8b43b192aa7dce0042bcf6bd5002f3bc"
  platform: esphome

packages:
  common: !include common/common.yaml

status_led:
  pin: 6

output:
  - platform: gpio
    id: relay
    pin: 7

button:
  - platform: template
    name: "${friendly_name} press button"
    icon: "mdi:gate"
    on_press:
      then:
        - output.turn_on: relay
        - delay: 300ms
        - output.turn_off: relay

logger:
  level: DEBUG

#cover:
# - platform: as5600_cover
#   name: Garage door

# esp32_ble_tracker:

sensor:
  # - platform: xiaomi_miscale
  #   mac_address: '5C:64:F3:51:17:A0'
  #   weight:
  #     name: "Bathroom 1 weight"
  #   impedance:
  #     name: "Bathroom 1 weight impedance"
  - platform: uptime
    type: seconds
    name: Uptime Sensor
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 15s
