packages:
  tuya: !include
    file: common/tuya-2-gang.yaml
    vars:
      device_name: laundry-lights
      channel_1_id: lights_1
      channel_2_id: lights_2

light:
  - platform: binary
    id: lights_1
    name: Laundry lights
    output: lights_1_output

  - platform: binary
    id: lights_2
    name: Laundry outdoor lights
    output: lights_2_output

binary_sensor:
  - id: !extend lights_1_sensor
    on_press:
      - light.toggle: lights_1

  - id: !extend lights_2_sensor
    on_press:
      - light.toggle: lights_2