esphome:
  name: media-room-blinds
  friendly_name: media-room-blinds

esp8266:
  board: esp01_1m

packages:
  common: !include common/common.yaml

uart:
  id: uart_instance
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  # debug:
  #   direction: BOTH
  #   dummy_receiver: false
  #   after:
  #     timeout: 50ms

cover:
  - platform: tuya_cover
    id: blinds
    name: "Media room blind"
    uart: uart_instance